apiVersion: apps.wuyong.cn/v2
kind: Application
metadata:
  name: application-sample-v2
  namespace: k8s-learn
  labels:
    app: application
spec:
  workflow:
    replicas: 11
    selector:
      matchLabels:
        app: application
    template:
      metadata:
        labels:
          app: application
      spec:
        containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
              - containerPort: 80
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        nodePort: 30080